# Path to your oh-my-zsh installation.
ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="clean"

# Uncomment the following line to disable bi-weekly auto-update checks.
DISABLE_AUTO_UPDATE="true"

# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
HIST_STAMPS="mm/dd/yyyy"

plugins=(git)

# User configuration for pip, don't run pip as root
# Use "pip2 install --user [package]" to install locally
export PATH="${PATH}:$HOME/.local/bin/"

# For ccache config: https://wiki.archlinux.org/index.php/Ccache
export PATH="/usr/lib/ccache/bin/:$PATH"

# Hardware Acceleration Stuff
export VDPAU_DRIVER=va_gl
export LIBVA_DRIVER_NAME=i965

#export TERM="screen-256color-bce"
export TERM="xterm-termite"
# export MANPATH="/usr/local/man:$MANPATH"

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vi'
else
  export EDITOR='vim'
fi

eval $(dircolors ~/.dircolors)
# Compilation flags
# export ARCHFLAGS="-arch x86_64"

BROWSER=/usr/bin/firefox-bin
# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"
alias rasp='mosh boris@192.168.1.50 --ssh="ssh -p6969" --port 60001'
alias wip="curl -s icanhazip.com"
alias fix0="configure.sh wlan0 managed"
alias fix1="configure.sh wlan1 managed"
alias pen0="configure.sh wlan0 monitor"
alias pen1="configure.sh wlan1 monitor"
alias pen2="configure.sh wlan2 monitor"


# Tmux shortcuts
alias tmux="tmux -2"


# Pacman & Yaourt shortcuts 
#alias pacu="pacman -Syyu --noconfirm"
#alias pacs="pacman -sS $1"
#alias paci="pacman -S $1"
#alias pacif="pacman -S $1 --noconfirm"
#alias pacr="pacman -R $1"
#alias pacrf="pacman -Rs $1"
#alias pacl="pacman -Sc && pacman-optimize"
#alias yaou="yaourt -Syyu --noconfirm"
#alias yaos="yaourt -sS $1"
#alias yaoi="yaourt -S $1"
#alias yaoif="yaourt -S $1 --noconfirm"
#alias yaor="yaourt -R $1 --noconfirm"

# Gentoo Linux portage shortcuts
# Searching for a packages
# Fast search
alias qs="qsearch $1"
# Thorough time consuming search
alias qss="emerge -sS $1"

# Preview useflags & version of a package
alias qp="emerge -pv $1"

# Searching for all available versions of a package
alias qa="equery list -po $1"

# Autounmasking a package, run dispatch-conf (qcu) to apply changes
alias qum="emerge --ask --autounmask-write $1"

# Updating portage
alias qu="emerge --sync"

# Installing updates
alias qui="emerge -uDNAav --with-bdeps=y @world"

# Installing package
alias qi="emerge -av $1"

# Dispatch-conf shortcut for updating configurations
alias qcu="dispatch-conf"

# Removing package
alias qr="emerge -C $1"

# Cleaning 
alias qcl="emerge --depclean && eclean-dist"



## Custom app shortcuts

# Killing chromium zombie processes (run as root)
alias ckill="killall chrome; ps aux |  grep chrome | grep -v 'grep' | awk '{print $2}' | xargs kill;"


alias mount="mount | column -t"

# Install scrot and pbpst
alias scrotp="scrot -cd5 /tmp/screenshot.png && pbpst -S -e png -f /tmp/screenshot.png"

# File encryption/decryption using SSL
# ssle [input] [output]
encbin() {openssl enc -aes-256-cbc -salt -in $1 -out $2}
decbin() {openssl enc -aes-256-cbc -d -in $1 > $2}
enctxt() {openssl enc -aes-256-cbc -a -salt -in $1 -out $2}
dectxt() {openssl enc -aes-256-cbc -a -d -in $1 > $2}

alias du="du -h"
alias df="df -h"

# Youtube single track audio download
alias youa="youtube-dl --no-playlist -x --write-all-thumbnails --audio-quality 0 -i -c $1"
alias youap="youtube-dl --yes-playlist -x --write-all-thumbnails --audio-quality 0 -i -c $1"
# Youtube video download
alias youv="youtube-dl -f \"bestvideo[height<=?1080][vcodec!=vp9]+bestaudio/best\""
alias youvp="youtube-dl --yes-playlist -f \"bestvideo[height<=?1080][vcodec!=vp9]+bestaudio/best\""

# MPV youtube playlist playback
mpvp() {
	playID="`echo -e "$1" | cut -d'=' -f3`";
	mpv "https://www.youtube.com/playlist?list=$playID";
}

# Optimizing PDF books for Kindle Paperwhite 2
alias kin="k2pdfopt $1 -dev kp2 -cmax 2 -s -g 0.5 -wt -1 -wrap+ -hy -ws -0.2"
# Wget with proper output file naming
alias wget="wget -c --content-disposition $1"

# Custom Functions that I use regularly
#wkill() {systemctl stop NetworkManager.service; rfkill block wifi all}
getlog() {grep -A3 -i $1 ~/.weechat/logs/*log | grep -v joined | grep -v "has quit" | cut -f2,3 | less}
getip() {grep -i $1 ~/.weechat/logs/*log | grep "joined" | cut -f3 | sort| uniq -u}
#wkill() {systemctl stop wicd.service; rfkill block wifi all}
wkill() {/etc/init.d/NetworkManager stop; rfkill block wifi all}
wstart() {rfkill unblock wifi all; fix0; /etc/init.d/NetworkManager start}
wnet() {netstat "-naultp"}
wmon() {nethogs "wlan0"}

Lss() {livestreamer "$1" "source"}
Lsh() {livestreamer "$1" "high"}
Lsm() {livestreamer "$1" "medium"}



# Git shortcuts
alias Gs="git status"
alias Ga="git add ."
alias Gc="git commit -m $1"
alias Gp="git push"


# Note taking app
n() {
  if [ "$1" = "today" ];
  then
    $EDITOR ~/notes/`date +%y%m%d`
  else
    $EDITOR ~/notes/"$*"
  fi
}
nls() {
  ls -c ~/notes/ | grep "$*"
}
ns() {
	egrep -RHi "$*" ~/notes/*
}
nrd() {
  cat ~/notes/"$*"
}
nwr() {
  $EDITOR ~/notes/"$*"
}


# Pyrit functions for WPA handshakes
# pirate [source] [destination] [BSSID]
pirate(){pyrit -r $1 -o $2 -b $3 strip}

# Reaver & Bully shortcuts
# Pix [bssid] [channel] [interface]
Pix(){bully -b $1 -c $2 -d $3}

usbstat(){cat /sys/bus/usb/devices/usb*/authorized_default}

# Disable usb devices to mitigate rubber ducky style attacks
usboff(){echo 0 > /sys/bus/usb/devices/usb*/authorized_default}

#Enable usb devices 
usbon(){echo 1 > /sys/bus/usb/devices/usb*/authorized_default}



ZSH_CACHE_DIR=$HOME/.oh-my-zsh-cache
if [[ ! -d $ZSH_CACHE_DIR ]]; then
  mkdir $ZSH_CACHE_DIR
fi
source "$HOME/.vim/bundle/gruvbox/gruvbox_256palette.sh"
source $ZSH/oh-my-zsh.sh
